[package]
name = "crypticcoin_proofs"
description = "Crypticcoin zk-SNARK circuits and proving APIs"
version = "0.5.0"
authors = [
    "Jack Grigg <jack@z.cash>",
]
homepage = "https://github.com/crypticcoin-renewed/librustcrypticcoin"
repository = "https://github.com/crypticcoin-renewed/librustcrypticcoin"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[dependencies]
bellman = { version = "0.11.1", default-features = false, features = ["groth16"] }
blake2b_simd = "1"
bls12_381 = "0.6"
byteorder = "1"
directories = { version = "4", optional = true }
ff = "0.11"
group = "0.11"
jubjub = "0.8"
lazy_static = "1"
minreq = { version = "2", features = ["https"], optional = true }
rand_core = "0.6"
wagyu-crypticcoin-parameters = { version = "0.2", optional = true }
crypticcoin_primitives = { version = "0.5", path = "../crypticcoin_primitives" }

[dev-dependencies]
criterion = "0.3"
rand_xorshift = "0.3"

[features]
default = ["local-prover", "multicore"]
bundled-prover = ["wagyu-crypticcoin-parameters"]
download-params = ["minreq"]
local-prover = ["directories"]
multicore = ["bellman/multicore"]

[lib]
bench = false

[[bench]]
name = "sapling"
harness = false
required-features = ["local-prover"]

[[example]]
name = "get-params-path"
required-features = ["directories"]

[[example]]
name = "download-params"
required-features = ["download-params"]

[badges]
maintenance = { status = "actively-developed" }
